In [3]:
import numpy as np
from scipy.sparse import isspmatrix
from sklearn.preprocessing import normalize
import markov_clustering as mcl
#adjacent matrix with self loops added:
A=np.array([[1,2,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            [2,1,3,1,0,0,0,0,0,0,0,0,0,0,0,0,0],
            [2,3,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            [0,0,0,1,2,0,4,0,0,0,0,0,0,0,0,0,0],
            [0,0,0,2,1,2,3,1,0,0,0,0,0,0,0,0,0],
            [0,0,0,0,2,1,4,0,0,0,0,1,0,0,0,0,0],
            [0,0,0,4,3,4,1,0,0,0,0,0,0,0,0,0,0],
            [0,0,0,0,0,0,0,1,3,4,0,2,0,0,0,0,0],
            [0,0,0,0,0,0,0,3,1,3,0,2,0,0,0,0,0],
            [0,0,0,0,0,0,0,0,3,1,4,0,0,0,0,0,0],
            [0,0,0,0,0,0,0,0,0,4,1,3,0,0,0,0,0],
            [0,0,0,0,0,1,0,2,4,0,3,1,0,0,0,0,0],
            [0,0,0,0,0,0,0,0,0,1,0,0,1,3,2,0,0],
            [0,0,0,0,0,0,0,0,0,0,0,0,3,1,3,4,0],
            [0,0,0,0,0,0,0,0,0,0,0,1,2,3,1,0,0],
            [0,0,0,0,0,0,0,0,0,0,0,0,0,4,0,1,0],
            [0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1]])
def expand(matrix,e):
    return np.linalg.matrix_power(matrix, e)
def inflate(matrix,r):
    return normalize(np.power(matrix,r),norm="l1",axis=0) 
def multiple(x):
    list1=[]
    for i in range(0,100,x):
        if i!=0:
            list1.append(i)
    return list1
list1=multiple(10)

In [5]:
def converged(matrix1, matrix2):
    if isspmatrix(matrix1) or isspmatrix(matrix2):
        return sparse_allclose(matrix1, matrix2)
    return np.allclose(matrix1, matrix2)
def iterate(matrix, expansion, inflation):
    matrix = expand(matrix, expansion)
    matrix = inflate(matrix, inflation)
    return matrix

In [23]:
def run_mcl(matrix, expansion=2, inflation=2,maxiterations=100):
    # Normalize
    matrix = normalize(matrix)

    # iterations
    for i in range(maxiterations):
       

        # store current matrix for convergence checking
        last_mat = matrix.copy()

        # perform MCL expansion and inflation
        matrix = iterate(matrix, expansion, inflation)
         
        #if i+1 in multiple(10):
           # print("Iteration {}".format(i + 1))
            #print(matrix)
            #print("clusters for {} iteration are {}".format(i+1,mcl.get_clusters(matrix)))
        #if i+1 == 10:
       #     print("FINAL ADJACENCY MATRIX AFTER 10 ItERATIONS:")
            #print(matrix)
           # print("clusters for {} iteration are {}".format(i+1,mcl.get_clusters(matrix)))
           # break;


        #Check for convergence
        if i % 1==0:
            if converged(matrix, last_mat):
                print("Converged after {} iteration{}".format(i + 1, "s" if i > 0 else ""))
                print("clusters for {} iteration are {}".format(i+1,mcl.get_clusters(matrix)))
                break;
    print("-" * 50)


In [24]:
run_mcl(A,expansion=2,inflation=1.5,maxiterations=100)

Converged after 19 iterations
clusters for 19 iteration are [(0, 1, 2), (3, 4, 5, 6), (7, 8, 9, 10, 11, 16), (12, 13, 14, 15)]
--------------------------------------------------


In [25]:
run_mcl(A,expansion=2,inflation=2.5,maxiterations=100)

Converged after 9 iterations
clusters for 9 iteration are [(0, 1, 2), (3, 4, 5, 6), (7, 8, 9, 10, 11), (7, 8, 10, 16), (7, 9, 10, 11), (12, 13, 14, 15)]
--------------------------------------------------


In [26]:
A=np.array([[1,1,1,1],
          [1,1,0,1],
          [1,0,1,0],
          [1,1,0,1]])
run_mcl(A,expansion=2,inflation=1.5,maxiterations=100)

Converged after 15 iterations
clusters for 15 iteration are [(0, 1, 2, 3)]
--------------------------------------------------


In [27]:
run_mcl(A,expansion=2,inflation=2.5,maxiterations=100)

Converged after 12 iterations
clusters for 12 iteration are [(0, 1, 3), (2,)]
--------------------------------------------------


In [8]:
run_mcl(A,expansion=2,inflation=2.1,maxiterations=100)

Converged after 10 iterations
--------------------------------------------------
clusters for final adjacency matrix [(0, 1, 2), (3, 4, 5, 6), (7, 8, 9, 10, 11), (7, 8, 9, 10, 11, 16), (12, 13, 14, 15)]
Final Adjacency Matrix


array([[1.00000000e+000, 1.00000000e+000, 1.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [1.13694362e-044, 1.13694362e-044, 1.13694362e-044,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [1.91923212e-022, 1.91923212e-022, 1.91923212e-022,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00

In [28]:
import re
def(list1):
    list1=[(0, 1, 2), (3, 4, 5, 6), (7, 8, 9, 10, 11), (7, 8, 9, 10, 11, 16), (12, 13, 14, 15)]
    string=str(list1)
    print(string)
    replacements = {'0': 'A', '1': 'B', '2': 'C', '3': 'D', '4': 'E' ,'5': 'F', '6': 'G', '7': 'H' , '8': 'J' , '9': 'K' , '10': 'L' , '11': 'M', '12': 'N', '13': 'P', '14': 'Q', '15': 'R', '16': 'S'}
    converted_text = re.sub('(\d+)', lambda m: replacements[m.group()],string)
    return converted_text

SyntaxError: invalid syntax (<ipython-input-28-591998411d51>, line 2)

In [39]:
matrix=np.array([[0.2],[0],[0.05],[0.25],[0],[0.35],[0.15]])
C=np.power(matrix,1.5)
N=normalize(C,norm="l1",axis=0)
inflate(matrix,1.5)

array([[0.18224583],
       [0.        ],
       [0.02278073],
       [0.25469629],
       [0.        ],
       [0.42190501],
       [0.11837214]])

In [40]:
print(N)

[[0.18224583]
 [0.        ]
 [0.02278073]
 [0.25469629]
 [0.        ]
 [0.42190501]
 [0.11837214]]
